/**
 * tools/input-shape.ts
 *
 * Builds the per-operation MCP input shape (TOOL-3, TOOL-4, design §3.2).
 *
 * `buildInputShape(op)` returns a `ZodRawShape` — a plain object of Zod pieces,
 * NOT a wrapped `z.object` — so the MCP SDK's `registerTool` can consume it
 * directly as `inputSchema` and derive the advertised JSON Schema from it. The
 * hand-written `optionsJsonSchema` / `ilovepdfInputSchemaJson` from the widget
 * server are DROPPED; Zod stays authoritative.
 *
 * The pieces are reused, not redefined:
 *   - `sources`     — `sourcesSchema` (array, min 1, each non-empty)
 *   - `output_path` — `outputPathSchema` (optional string)
 *   - `options`     — a LOOSENED copy of the per-op `op.optionsSchema` (DEC-6).
 *
 * ## DEC-6 — Loosened options schema at the SDK boundary
 *
 * The per-op `optionsSchema` entries use strict Zod enums/types. When the SDK
 * validates the tool input against the strict schema, a bad option value (e.g.
 * `compression_level:'ultra'`) is rejected at the SDK layer before the handler
 * runs — producing an untyped `-32602` protocol error with NO `structuredContent`
 * or `error_code` (violates ERR-8/DEC-5).
 *
 * Fix: `loosenOptionsSchema()` derives a "loosened" shape where every field's
 * VALUE type is replaced with `z.unknown().optional()` while KEEPING:
 *   - The original key names (model discoverability — JSON Schema lists them).
 *   - The original `.describe()` text (model reads field descriptions).
 *   - `.passthrough()` on the wrapper (unknown/future keys survive).
 *
 * Any bad value that slips through the loosened SDK schema is then caught by
 * `validateOptions(op.name, args.options)` inside `makeHandler`, which throws
 * `ToolError('VALIDATION_ERROR', …)` — surfaced via the structured error path.
 *
 * Cardinality (exactly-one vs. many sources) is enforced in the handler, not
 * here — a second source for a single-file op is a `VALIDATION_ERROR`, not a
 * silently dropped file.
 */

import { z, type ZodRawShape } from 'zod';
import type { OperationSpec } from '../domain/operation-types.js';
import { sourcesSchema, outputPathSchema } from '../contract/input-schema.js';

// ---------------------------------------------------------------------------
// DEC-6: Loosen the options schema for the SDK boundary
// ---------------------------------------------------------------------------

/**
 * Derive a "loosened" options Zod schema from a per-op strict options schema.
 *
 * Keys and field descriptions are preserved so the JSON Schema advertised to
 * clients (via `tools/list`) still shows option names and their documentation.
 * Value types are widened to `z.unknown().optional()` so the MCP SDK accepts
 * any supplied value — the handler is then responsible for typed validation.
 *
 * If the schema cannot be structurally introspected (i.e. is not a ZodObject),
 * falls back to `z.record(z.unknown()).optional()` (permissive, no key names).
 */
function loosenOptionsSchema(schema: z.ZodTypeAny): z.ZodTypeAny {
  // Unwrap an outer ZodOptional wrapper (op.optionsSchema is not optional at
  // the top level, but be defensive in case the shape changes in future).
  const inner = schema instanceof z.ZodOptional ? schema.unwrap() : schema;

  // All per-op options schemas are z.object({...}).passthrough(). Only handle
  // ZodObject — fall back to a permissive record for anything else.
  if (!(inner instanceof z.ZodObject)) {
    return z.record(z.unknown()).optional();
  }

  const originalShape = inner.shape as ZodRawShape;
  const loosenedShape: ZodRawShape = {};

  for (const [key, fieldSchema] of Object.entries(originalShape)) {
    // Preserve the description from the original field schema so the JSON Schema
    // generated by the SDK still documents each option for model discoverability.
    const description = (fieldSchema as z.ZodTypeAny).description;
    let loosened: z.ZodTypeAny = z.unknown().optional();
    if (description) {
      loosened = loosened.describe(description);
    }
    loosenedShape[key] = loosened;
  }

  // Keep .passthrough() so unknown keys (e.g. future iLovePDF API params)
  // still survive the SDK boundary and reach the upstream API.
  return z.object(loosenedShape).passthrough().optional();
}

// ---------------------------------------------------------------------------
// Public: buildInputShape
// ---------------------------------------------------------------------------

/**
 * Returns the `ZodRawShape` for a single operation's tool input.
 * See design §3.2 and DEC-6 (loosened options schema).
 */
export function buildInputShape(op: OperationSpec): ZodRawShape {
  return {
    sources: sourcesSchema,
    output_path: outputPathSchema,
    options: loosenOptionsSchema(op.optionsSchema).describe(
      'Operation-specific options.'
    ),
  };
}
